### ISSUE TITLE
401 errors on MIT Open CI

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1137]
# User Story

I am distracted by the many 401 errors in Sentry from MIT Open 

# Description/Context

All the errors are coming from CI: https://sentry.io/organizations/mit-office-of-digital-learning/issues/?environment=ci&project=216201&query=is%3Aunresolved+401&statsPeriod=14d

Are they relevant? Can we fix them, or quiet them?

**Comment by Ardiea** [comment]
I will take a look today. Probably a configuration error somewhere.

**Comment by Ardiea** [comment]
THis should be resolved. I updated the CI environment configuration to point to the actual CI open search infrastructure (it was pointing at RC/QA before), populated a few things missing in vault and then fired of a recreate --all command in heroku so that it has data at the indices it expects, just to be sure.
