### ISSUE TITLE
Migrate Zendesk SSO to use Touchstone directly

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1252]
# User Story
As a user of Zendesk I would like to ensure that authentication/login is always available and reliable.

# Description/Context
We currently rely on our outdated and unmaintained CAS server for providing Touchstone auth to Zendesk. We need to migrate this to use the direct SAML integration offered by Zendesk.

# Acceptance Criteria
- [ ] Zendesk login no longer relies on the CAS server

**Comment by blarghmatey** [comment]
The documentation for enabling SAML auth in Zendesk is available at https://support.zendesk.com/hc/en-us/articles/4408887505690-Enabling-SAML-single-sign-on

**Comment by blarghmatey** [comment]
The auth flow was not actually using Touchstone directly. It was implicitly using CAS via the external-user login instead.

**Comment by shaidar** [comment]
@pdpinch Can you please make me a Zendesk admin so that I can start looking into this.

**Comment by pdpinch** [comment]
You are now an admin. 

Let me know when I can revert your permissions.

**Comment by shaidar** [comment]
@blarghmatey Logging into Zendesk admin, I notice that we already have an MIT SAML option that's pointing to ISTs IDP. Have we already registered this SP with the IDP or that something we still need to do?

**Comment by shaidar** [comment]
Appears that the least disruptive approach once we've verified that all is configured as it should:
- [ ] SP is registered with the Touchstone IDP
- [ ] Verify current configs in Zendesk Admin

We should be able to make Touchstone as a selectable option for team members (not end users) and that way if we run into problems, they would still be able to login using the existing web token option. The current config is shown in the screenshot below.

![Screenshot 2023-08-04 at 12 13 55 PM](https://github.com/mitodl/ol-infrastructure/assets/1447295/c1ee4157-b72f-40ca-bd54-615e65d69595)

**Comment by shaidar** [comment]
@pdpinch Is the [`Zendesk Authentication`](https://odl.zendesk.com/admin/account/security/team_members) option still used/needed?

**Comment by blarghmatey** [comment]
It's already registered, but I am not clear on why it was still using CAS. We might need to do more work on configuration on the IDP side

**Comment by shaidar** [comment]
Yeah just added my IP to use touchstone and eventually landed in CAS land. Will dig deeper to see why that's the case.

**Comment by shaidar** [comment]
I tried using IP filtering to enable MIT SAML for my IP in the hopes of getting redirected to the Touchstone IDP, but I was still gong through CAS for some reason with the wrong entity_id. Also tried clicking the button to where team members get to choose between CAS and Touchstone, but that didn't seem to change anything either. So, can't really tell yet why I'm not seeing the impact of those changes.

**Comment by shaidar** [comment]
I reached out to Zendesk support through their chatbot and the expected response time is about a day or two. In the meantime, my guess is that the issue might be related to having the Cloudflare cache handling requests. Tried the IP range, but that's still behaving the same way. I even made the change to let a team member select which auth to use, however nothing changed when trying to logon. Looked through the requests/responses and appears that Cloudflare is being used and that's where I'm guessing the problem lies. Maybe the IP range isn't being passed as one of the headers and that probably explains why changing settings in the web portal isn't reflected in expected app behavior as well.

**Comment by shaidar** [comment]
Haven't heard from Zendesk support yet on this. Will ping them again tomorrow if they hadn't reached out at that point.

**Comment by shaidar** [comment]
Got a contact email from support and reached out to see if we can schedule a call to look into this.

**Comment by shaidar** [comment]
Tried again using IP filtering just to make sure nothing has changed on the Zendesk end and ran into the same previous issue where even though my IP should be trying to use SAML over CAS, I end up authing to CAS. Emailed our Zendesk contact. In the meantime, will take another look at the requests to try and piece together why/where the CAS entity ID is getting pulled from.

**Comment by shaidar** [comment]
This is now resolved and team members logging in will see two options and at this point, both should work:
![Screenshot 2024-03-04 at 11 35 28 AM](https://github.com/mitodl/ol-infrastructure/assets/1447295/cc14a995-8a91-4e95-9dcf-06c97aaa7dee)
The two main issues we encountered were:
- We were using a custom theme on mitx-support and thus all the changes made in the admin console weren't showing because of that. Switched to using the Zendesk Copenhagen theme which then automatically reflects any changes made in the Admin console.
- When testing changes made in the admin console to team members, we should be checking the `/agent` endpoint, otherwise it'll be the end-user endpoint and won't reflect any of the changes made in the admin panel, unless of course, the changes were made at the end-user level.

I tested logging in through Touchstone and that appears to be working and I also asked Quasi to login (doesn't have an account) to verify that authz is handled properly at the Zendesk app and that appears to be the case. Notified Tim about the change and requested that the team try it out and let us know.

**Comment by shaidar** [comment]
Made the change to redirect all users to using Touchstone. Haven't removed the CAS config just in case, but we should probably give it a few days and then do that cleanup.

**Comment by blarghmatey** [comment]
@shaidar when can we do any necessary cleanup and close this out?

**Comment by shaidar** [comment]
@blarghmatey Was tempted to remove the entries from Zendesk, but figured since CAS is still around, maybe just leave them as a backup until CAS is completely retired.

**Comment by blarghmatey** [comment]
@shaidar as part of fully retiring the CAS server can we remove those entries from Zendesk and close this ticket?

**Comment by shaidar** [comment]
Entry has been removed.
