### ISSUE TITLE
Replace caddy with traefik for tika and concourse

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1425]
# User Story
- As a platform owner I want to reduce the number of technologies in use

# Description/Context
We are standardizing on Traefik for all of our proxying. Caddy is still in use for Concourse and Tika images so we would like to remove it from our infrastructure.

# Acceptance Criteria
- [ ] Concourse is using Traefik as its proxy
- [ ] Tika is using Traefik as its proxy
- [ ] Code for managing Caddy is removed from ol-infrastructure

**Comment by blarghmatey** [comment]
@shaidar this will be a good opportunity to familiarize yourself with Traefik. @Ardiea can help with details from his own experience building with Traefik.

**Comment by feoh** [comment]
Trying to mimic the Vault traefik configuration was, I feel, a mistake.

That configuration uses custom transport (Vault) rather than https/TLS/LetsEncrypt.

When I get back from vacation I am going to jettison my current branch and start afresh simply working from the Traefik docs. Our use case is incredibly simple and should be very easy to replicate.

**Comment by feoh** [comment]
Realized this bug is behind on status. Concourse has been in production since early last week. Working on Tika now. Converting the Tika build to docker to fix multiple problems in one go.

**Comment by feoh** [comment]
We're going to block this on @mbertrand's return from vacation. It's deployed to CI and QA/RC with no issue. No sense rushing the production deploy when it's not time critical.
