### ISSUE TITLE
Fork/Build Concourse ARM Images for Apple Silicon

### ISSUE THREAD

**Issue by pt2302** [mitodl/ol-infrastructure#1918]
# Description/Context
In the OCW project, [developers using Apple Silicon](https://github.com/mitodl/ocw-studio#running-ocw-studio-on-apple-silicon) rely on an ARM image of Concourse for local development. Updates to the Concourse version, such as https://github.com/mitodl/ocw-studio/issues/2021, require that an Apple Silicon version of the Concourse container is available.

# Plan/Design
Investigate using one of the EC2 M2 instances to build the Concourse ARM images.

**Comment by Ardiea** [comment]
@pt2302 I'm a little unclear here on what you're looking for.

- You want devops to build+publish a docker image for arm64_mac that developers can use as part of their local workflow? 
- You want devops to add arm64_mac EC2 instances to our concourse worker pools and transition the OCW workloads to those instances so that the developer + production workflows match in architecture? 
- Something else or something in between? 

The EC2 M2 mac instances are pretty specialized and expensive when compared to what we typically run. Compared vs AWS "Graviton" instances which are also ARM64 but are typically less expensive than x86-64 machines.

**Comment by feoh** [comment]
No longer needed. Now that docker desktop provides out of box performant support for Intel images this feels unnecessary to me.
