### ISSUE TITLE
Set up automatic cycling of OCW Concourse workers

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ol-infrastructure#2164]
### Description/Context
Occasionally, OCW site pipelines will fail with messages similar to `run check: find or create container on worker ip-10-0-1-142: volume mounted to container is missing 'fa54e9cb-7178-4181-555d-8a372ce4e8ae' from worker 'ip-10-0-1-142'` or other similar error messages about workers not responding. This is generally solved by cycling out the worker instances. It would be nice to do this on a regular basis for OCW workers to prevent them getting "stale."

**Comment by feoh** [comment]
This isn't resolved.

In order to add the 3AM start time @gumaerc signposted we need in order to avoid disruptng OCW production.

I thought this was an easy fix so I dived in but it's taken most of the day and right now my changes from the latest PR are failing (no definition for build_schedule) when I try to update the pipeline.

So I'm going to revert my changes to main. My work on this up to this point can be seen in https://github.com/mitodl/ol-infrastructure/pull/2166

Whenever someone picks this up, somehow we need additional code here to actually include the definition for the build_schedule resource, because right now when I try to apply this I get:
```

pipeline name: instance-refresh-concourse

apply configuration? [yN]: y
error: invalid pipeline config:
invalid jobs:
        jobs.ci-worker-infra-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.ci-worker-ocw-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.ci-worker-generic-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.ci-web-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.qa-worker-infra-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.qa-worker-ocw-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.qa-worker-generic-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.qa-web-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.production-worker-infra-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.production-worker-ocw-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.production-worker-generic-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'
        jobs.production-web-instance-refresh.plan.do[0].get(build-schedule): unknown resource 'build-schedule'

```
