### ISSUE TITLE
Refactor OpenSearch stacks to use opensearch resource instead of elasticsearch

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#2358]
### Description/Context

Our deployments of OpenSearch clusters managed on AWS are currently provisioned using the [elasticsearch](https://www.pulumi.com/registry/packages/aws/api-docs/elasticsearch/) module of the AWS Pulumi SDK. This is functional, but doesn't support the full surface area of the OpenSearch service. In particular, it doesn't allow for automatically applying version updates as part of the provisioning. The newer [opensearch](https://www.pulumi.com/registry/packages/aws/api-docs/opensearch/) module has all of the supported features that we want. It also supports the new serverless offering, which we might want to consider using.

In order to make full use of the AWS service we need to migrate our existing clusters to use the new module without incurring downtime.

### Plan/Design

It should be possible to rewrite our code to use the new interface without having to terminate and rebuild clusters. Using the alias and/or import functionality should allow us to use the current clusters as-is. As part of this refactor we should also convert the code to use component resources for simplifying their interface.

**Comment by Ardiea** [comment]
OK! Took some experiementation and I accidentally blew away the xPro-CI opensearch cluster. Whoops! Oh well. 

(Partial?) Procedure:
1. First add `retain_on_delete=True` to all `aws.elasticsearch` resources in the stack. This is its own thing, done in isolation from the next step.
2. Refactor the existing resources to `aws.opensearch`. Couple little nuances but otherwise straightforward. As part of this add `import_=<appropriate string for the resource type>`.

Should result in a two part stack update like that looks like this. Note that this one is only working with the `Domain`. For real, we would need to do the `DomainPolicy` as well. 

```
     Type                               Name                                                                Plan               Info
     pulumi:pulumi:Stack                ol-infrastructure-opensearch-infrastructure.aws.opensearch.xpro.CI                     1 warning
     ├─ pulumi:providers:consul         consul-provider
     ├─ consul:index:Node               aws-opensearch-consul-node
     ├─ consul:index:Keys               elasticsearch
     ├─ aws:elasticsearch:DomainPolicy  opensearch-domain-cluster-access-policy
     ├─ consul:index:Service            aws-opensearch-consul-service
     ├─ aws:ec2:SecurityGroup           opensearch-security-group
 ~   ├─ pulumi:pulumi:StackReference    infrastructure.vault.operations.CI                                  refresh
 ~   ├─ pulumi:pulumi:StackReference    infrastructure.consul.xpro.CI                                       refresh
 -   ├─ aws:elasticsearch:Domain        opensearch-domain-cluster                                           delete[retain]
 ~   ├─ pulumi:pulumi:StackReference    infrastructure.aws.network.CI                                       refresh
 =   └─ aws:opensearch:Domain           opensearch-v2-domain-cluster                                        import             [diff: ~cluste
```

Now, because we don't actually have any relationships between resources defined in these stacks (parents+children), I don't believe that we need to do anything with `aliases`. 

3. (Untested) A third and final step would be to remove `retain_on_delete` and `import_` from the stacks now that they are migrated to `aws.opensearch`. 
4. Profit?

**Comment by Ardiea** [comment]
```
Pulumi.infrastructure.aws.opensearch.xpro.CI.yaml						DONE
Pulumi.infrastructure.aws.opensearch.apps.CI.yaml						HOLD - Password issues ?
Pulumi.infrastructure.aws.opensearch.celery_monitoring.CI.yaml			DONE
Pulumi.infrastructure.aws.opensearch.mitx-staging.CI.yaml					DONE
Pulumi.infrastructure.aws.opensearch.mitx.CI.yaml						DONE
Pulumi.infrastructure.aws.opensearch.open.CI.yaml						HOLD - Password issues ?


Pulumi.infrastructure.aws.opensearch.apps.QA.yaml						HOLD - Password issues ?
Pulumi.infrastructure.aws.opensearch.celery_monitoring.QA.yaml			DONE
Pulumi.infrastructure.aws.opensearch.mitopen.QA.yaml						HOLD - Password issues ?
Pulumi.infrastructure.aws.opensearch.mitx-staging.QA.yaml					DONE
Pulumi.infrastructure.aws.opensearch.mitx.QA.yaml						DONE
Pulumi.infrastructure.aws.opensearch.open.QA.yaml						HOLD - Password issues ?
Pulumi.infrastructure.aws.opensearch.xpro.QA.yaml						DONE
Pulumi.infrastructure.aws.opensearch.mitxonline.QA.yaml					DONE


Pulumi.infrastructure.aws.opensearch.apps.Production.yaml					WAIT
Pulumi.infrastructure.aws.opensearch.celery_monitoring.Production.yaml		WAIT
Pulumi.infrastructure.aws.opensearch.mitopen.Production.yaml				WAIT
Pulumi.infrastructure.aws.opensearch.mitx-staging.Production.yaml			WAIT
Pulumi.infrastructure.aws.opensearch.mitx.Production.yaml					WAIT
Pulumi.infrastructure.aws.opensearch.mitxonline.Production.yaml			WAIT
Pulumi.infrastructure.aws.opensearch.open.Production.yaml					WAIT
Pulumi.infrastructure.aws.opensearch.xpro.Production.yaml					WAIT
```

The import isn't working for a handful of clusters because it thinks there is an issue with the master user password. I havne't looked into it further yet. The ones having the issue happen to overlap with the ones that are having issues because they are in the same VPC (apps). I think I need to code in a "just don't do any consul stuff" flag to fix that problem.
