### ISSUE TITLE
Container Management POC

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#531]
We are increasingly in need of a smooth way to get containerized workloads into a production environment. To that end, we want to invest in building the infrastructure and tooling necessary to support application and service deployment as containers. We have looked at Nomad in the past due to its easy integration with Vault and Consul which we use extensively, but the weight of the community favors Kubernetes. Given our perennial challenge of testing out new systems quickly, we will likely want to get a proof of concept working on Kubernetes to identify any unknown unknowns. As a first pass we can work on getting the edx-notes-api running in a Kubernetes cluster running on Amazon EKS in a pre-production environment.

We will want to timebox this task to ~1-2 weeks and the outcome should be:
- [ ] A go/no-go decision on whether to stick with Kubernetes
- [ ] A list of additional services/system design requirements
- [ ] A functional integration with Vault and Consul for secrets and service discovery respectively

**Comment by mschuchard** [comment]
Notes from discussion for PoC:
- EKS 1.21 in PoC, but 1.22 in production (AWS release scheduled for March)
- Setup ingress with Traefik
- Setup service mesh sidecars with Consul
- Setup secrets injection sidecar for Vault agent
- Create standardized templated manifest for application workloads
- - deployment
- - service
- - ingress
- Deploy EDX-notes-API to cluster and acceptance test

**Comment by mschuchard** [comment]
Outstanding issues:
- The traefik external IP address for the load balancer service corresponding to the automatically provisioned AWS load balancer  needs a Route53.
- Traefik ingress, routes, and entrypoints config all likely need updates after testing after implementing the above.
- The edx-notes-api Probes all check on ports 20300/20400 instead of the designated http port at 8120 for some reason (possibly the Consul service mesh according to Tobias).
- The Vault agent sidecar injector does not successfully authenticate against the Vault server. This is likely due to a connection/traffic issue, but skipping TLS verification does not seem to improve the situation.
