### ISSUE TITLE
Enable GitHub auth for Vault servers

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#687]
In order to smooth the process of giving developers access to AWS resources and manage application secrets we want to set up the GitHub authentication mechanism. This will also require creating and maintaining a policy definition that will be assigned based on GitHub team membership.

**Comment by shaidar** [comment]
@blarghmatey What resources are we planning on providing Github team members? The reason I ask is so that we can have a clear idea about the default policy to assign them. Based on [vault doc](https://www.vaultproject.io/docs/auth/github) it appears that we can add individual policies in addition to the group one, but would be good to hash out the default group one at first.

**Comment by blarghmatey** [comment]
This has been enabled across our environments, with developers having read access in CI and QA stages and production being limited to DevOps team members
